version: "3.9"

services:
  backend_mock:
    container_name: mock_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:3005"
    restart: always

  frontend_mock:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    depends_on:
      - backend_mock
    container_name: mock_chat
    ports:
      - '9000:80'
    restart: on-failure

